package com.codepath.apps.restclienttemplate.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIRECT_MESSAGE.
 */
public class DirectMessage {

    private Long internalId;
    private Long id;
    private String text;
    private String sender_screen_name;

    public DirectMessage() {
    }

    public DirectMessage(Long internalId) {
        this.internalId = internalId;
    }

    public DirectMessage(Long internalId, Long id, String text, String sender_screen_name) {
        this.internalId = internalId;
        this.id = id;
        this.text = text;
        this.sender_screen_name = sender_screen_name;
    }

    public Long getInternalId() {
        return internalId;
    }

    public void setInternalId(Long internalId) {
        this.internalId = internalId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getSender_screen_name() {
        return sender_screen_name;
    }

    public void setSender_screen_name(String sender_screen_name) {
        this.sender_screen_name = sender_screen_name;
    }

}
